import RangeSum from './RangeSum';
import InvertBinaryTree from './InvertBinaryTree';
import MergeTwoBinaryTrees from './MergeTwoBinaryTrees';
import MaximumDepthOfBinaryTree from './MaxDepthBinaryTree';
import DiameterOfBinaryTree from './DiameterOfBinaryTree';
import SymmetricTree from './SymmetricTree';
import PathSum3 from './PathSum3';
import FlattenBinaryTree from './FlattenBinaryTree';
import BinaryTreeInorderTraversal from './BinaryTreeInorderTraversal';
import BinaryPreorderTraversal from './BinaryTreeInorderTraversal';
import BinaryTreeLevelOrderTraversal from './BinaryTreeLevelOrderTraversal';
import UniqueBinaryTrees from './UniqueBinaryTrees';
import ConstructBSTFromPreorderAndInorderTraversal from './ConstructBSTFromPreorderAndInorder';
import ImplementPrefixTrie from './ImplementPrefixTrie';
import LowestCommonAncestorOfBST from './LowestCommonAncestorOfABST';
import ValidateBinarySearchTree from './ValidateBinarySearchTree';
import ConvertedSortedArrayIntoBST from './ConvertSortedArrayIntoBST';
import KthSmallestElementInBST from './KthSmallestElementInBST';
import BSTZigZagOrderTraversal from './BSTZigZagOrderTraversal';
import PopulatingNextRightPointersInEachNode from './PopulatingNextRightPointersInEachNode';
import BinaryTreeRightSideView from './BinaryTreeRightSideView';
import SerialAndDeserializeBT from './SerialAndDeserializeBT';

const TreesMain = () => {
    // PopulatingNextRightPointersInEachNode();
    // RangeSum();
    // InvertBinaryTree();
    // MergeTwoBinaryTrees();
    // MaximumDepthOfBinaryTree();
    // DiameterOfBinaryTree();
    // SymmetricTree();
    PathSum3();
    // FlattenBinaryTree();
    // BinaryPreorderTraversal();
    // BinaryTreeLevelOrderTraversal();
    // BinaryTreeRightSideView();
    // UniqueBinaryTrees();
    // ConstructBSTFromPreorderAndInorderTraversal();
    // ImplementPrefixTrie();
    // LowestCommonAncestorOfBST();
    // ValidateBinarySearchTree();
    // ConvertedSortedArrayIntoBST();
    // BinaryTreeInorderTraversal();
    // KthSmallestElementInBST();
    // BSTZigZagOrderTraversal();
    // SerialAndDeserializeBT();
};

export default TreesMain;
