import FindKPairsWithSmallestSums from './FindKPairsWithSmallestSums';
import FindMedianFromDataStream from './FindMedianFromDataStream';
import JavascriptHeapArray from './JavascriptHeapArray';
import KClosestPointsToOrigin from './KClosestPointsToOrigin';
import KthLargestElementInAnArray from './KthLargestElementInAnArray';
import LongestHappyString from './LongestHappyString';
import MaximumSwap from './MaximumSwap';
import MinHeapConstruction from './MinHeapConstruction';
import RearrangeStringKDistanceApart from './RearrangeStringKDistanceApart';
import ReorganizeString from './ReorganizeString';
import SlidingWindowMedian from './SlidingWindowMedian';
import SmallestRangeCoveringElementsFromKLists from './SmallestRangeCoveringElementsFromKLists';
import SortCharactersByFrequency from './SortCharactersByFrequency';
import StockPriceFluctation from './StockPriceFluctation';
import TopKFrequentElements from './TopKFrequentElements';

export default () => {
  // FindKPairsWithSmallestSums();
  // FindMedianFromDataStream();
  // JavascriptHeapArray();
  // KClosestPointsToOrigin();
  // KthLargestElementInAnArray();
  // LongestHappyString();
  // MaximumSwap();
  // MinHeapConstruction();
  // RearrangeStringKDistanceApart();
  // ReorganizeString();
  // SlidingWindowMedian();
  // SmallestRangeCoveringElementsFromKLists();
  // SortCharactersByFrequency();
  // StockPriceFluctation();
  // TopKFrequentElements();
};
