import ValidParentheses from './ValidParentheses';
import MinimumWindowSubstring from './MinimumWindowSubstring';
import DecodeString from './DecodeString';
import FindAllAnagramsInAString from './FindAllAnagramsInAString';
import WordBreak from './WordBreak';
import ReverseString from './ReverseString';
import FizzBuzz from './FizzBuzz';
import ValidAnagram from './ValidAnagram';
import RomanToInteger from './RomanToInteger';
import FirstUniqueCharInAString from './FirstUniqueCharacterInString';
import PartitionLabels from './PartitionLabels';
import CountAndSay from './CountAndSay';
import ValidPalindrome from './ValidPalindrome';
import ImplementStrStr from './ImplementStrStr';
import ReverseInteger from './ReverseInteger';
import ToLowerCase from './ToLowerCase';
import CaesarCipherEncryptor from './CaesarCipherEncryptor';
import RunLengthEncoding from './RunLengthEncoding';
import GenerateDocument from './GenerateDocument';
import FirstNonRepeatingCharacter from './FirstNonRepeatingCharacter';
import LongestPalindromicSubstring from './LongestPalindromicSubstring';
import GroupAnagrams from './GroupAnagrams';
import ValidIPAddresses from './ValidIPAddresses';
import ReverseWordsInString from './ReverseWordsInString';
import MinimumCharacterForWords from './MinimumCharacterForWords';
import LongestSubstringWithoutDuplication from './LongestSubstringWithoutDuplication';
import UnderscorifySubstring from './UnderscorifySubstring';
import BackspaceStringCompare from './BackspaceStringCompare';
import KnuthMorrisPratt from './KnuthMorrisPratt';
import BoyerMooreAlgorithm from './BoyerMooreAlgorithm';
import IndexPairsOfAString from './IndexPairsOfAString';
import CountUniqueCharactersOfAllSubstringsOfAGivenString from './CountUniqueCharactersOfAllSubstringsOfAGivenString';

export default () => {
  // BackspaceStringCompare();
  // BoyerMooreAlgorithm();
  // CaesarCipherEncryptor();
  // CountUniqueCharactersOfAllSubstringsOfAGivenString();
  // CountAndSay();
  // DecodeString();
  // FindAllAnagramsInAString();
  // FirstNonRepeatingCharacter();
  // FirstUniqueCharInAString();
  // FizzBuzz();
  // GenerateDocument();
  // GroupAnagrams();
  // ImplementStrStr();
  // IndexPairsOfAString();
  // KnuthMorrisPratt();
  // LongestPalindromicSubstring();
  // LongestSubstringWithoutDuplication();
  // MinimumCharacterForWords();
  // MinimumWindowSubstring();
  // PartitionLabels();
  // ReverseInteger();
  // ReverseString();
  // ReverseWordsInString();
  // RomanToInteger();
  // RunLengthEncoding();
  // ToLowerCase();
  // UnderscorifySubstring();
  // ValidAnagram();
  // ValidIPAddresses();
  // ValidParentheses();
  // ValidPalindrome();
  // WordBreak();
};
