import ValidParentheses from './ValidParentheses';
import MinimumWindowSubstring from './MinimumWindowSubstring';
import DecodeString from './DecodeString';
import FindAllAnagramsInAString from './FindAllAnagramsInAString';
import WordBreak from './WordBreak';
import ReverseString from './ReverseString';
import FizzBuzz from './FizzBuzz';
import ValidAnagram from './ValidAnagram';
import RomanToInteger from './RomanToInteger';
import FirstUniqueCharInAString from './FirstUniqueCharacterInString';
import PartitionLabels from './PartitionLabels';
import CountAndSay from './CountAndSay';
import ValidPalindrome from './ValidPalindrome';
import ImplementStrStr from './ImplementStrStr';
import ReverseInteger from './ReverseInteger';
import ToLowerCase from './ToLowerCase';

export default () => {
    ToLowerCase();
    // ValidParentheses();
    // PartitionLabels();
    // MinimumWindowSubstring();
    // DecodeString();
    // FindAllAnagramsInAString();
    // WordBreak();
    // ReverseString();
    // FizzBuzz();
    // ValidAnagram();
    // RomanToInteger();
    // FirstUniqueCharInAString();
    // CountAndSay();
    // ValidPalindrome();
    // ImplementStrStr();
    // ReverseInteger();
};
