import Permutations from './Permutations';
import GenerateParentheses from './GenerateParentheses';
import Subsets from './Subsets';
import CombinationSum from './CombinationSum';
import TargetSum from './TargetSum';
import LetterCombinationsOfAPhoneNumber from './LetterCombinationsOfAPhoneNumber';
import SubarraySumEqualsK from './SubarraySumEqualsK';
import Fibonacci from './Fibonacci';
import ProductSum from './ProductSum';
import Powerset from './Powerset';
import StaircaseTraversal from './StaircaseTraversal';
import LowestCommonManager from './LowestCommonManager';
import InterweavingStrings from './InterweavingStrings';
import Sudoku from './Sudoku';

export default () => {
    // CombinationSum();
    // Fibonacci();
    // GenerateParentheses();
    // InterweavingStrings();
    // LetterCombinationsOfAPhoneNumber();
    // LowestCommonManager();
    // Permutations();
    // Powerset();
    // ProductSum();
    Sudoku();
    // StaircaseTraversal();
    // SubarraySumEqualsK();
    // Subsets();
    // TargetSum();
};
