import RotateImage from './RotateImage';
import UniquePaths from './UniquePaths';
import MinimumPathSum from './MinimumPathSum';
import NumberOfIslands from './NumberOfIslands';
import SearchA2DMatrix2 from './SearchA2DMatrix2';
import MaximalSquare from './MaximalSquare';
import WordSearch from './WordSearch';
import GameOfLife from './GameOfLife';
import KthSmallestElementInSortedMatrix from './KthSmallestElementInSortedMatrix';
import ValidSudoku from './ValidSudoku';
import SetMatrixZeroes from './SetMatrixZeroes';
import RottingOranges from './RottingOranges';
import SpiralTraversal from './SpiralTraversal';
import RiverSizes from './RiverSizes';
import RemoveIslands from './RemoveIslands';
import ZigZagTraversal from './ZigZagTraversal';
import WaterfallStreams from './WaterfallStreams';
import MinimumPassesOfMatrix from './MinimumPassesOfMatrix';
import BoggleBoard from './BoggleBoard';

export default () => {
  BoggleBoard();
    // GameOfLife();
    // KthSmallestElementInSortedMatrix();
    // MaximalSquare();
    // MinimumPathSum();
    // MinimumPassesOfMatrix();
    // NumberOfIslands();
    // RemoveIslands();
    // RiverSizes();
    // RotateImage();
    // RottingOranges();
    // SearchA2DMatrix2();
    // SetMatrixZeroes();
    // SpiralTraversal();
    // WordSearch();
    // UniquePaths();
    // ValidSudoku();
    // WaterfallStreams();
    // ZigZagTraversal();
};
