import BinarySearch from "./BinarySearch";
import BitonicArrayMaximum from "./BitonicArrayMaximum";
import CeilingOfANumber from "./CeilingOfANumber";
import CountOfRangeSum from "./CountOfRangeSum";
import FindKClosestElements from "./FindKClosestElements";
import FindMinimumInRotatedSortedArray from "./FindMinimumInRotatedSortedArray";
import FindPeakElement from "./FindPeakElement";
import FindSmallestLetterGreaterThanTarget from "./FindSmallestLetterGreaterThanTarget";
import FindThreeLargestNums from "./FindThreeLargestNums";
import MedianOfTwoSortedArrays from "./MedianOfTwoSortedArrays";
import MinimumDifferenceElement from "./MinimumDifferenceElement";
import NextLetter from "./NextLetter";
import NumberRange from "./NumberRange";
import OrderAgnosticBinarySearch from "./OrderAgnosticBinarySearch";
import PeakIndexInAMountainArray from "./PeakIndexInAMountainArray";
import RotationCount from "./RotationCount";
import SearchA2DMatrix from "./SearchA2DMatrix";
import SearchA2DMatrix2 from "./SearchA2DMatrix2";
import SearchBitonicArray from "./SearchBitonicArray";
import SearchInASortedInfiniteArray from "./SearchInASortedInfiniteArray";
import SearchInRotatedArray from "./SearchInRotatedArray";
import SearchInRotatedArray2 from "./SearchInRotatedArray2";
import SearchInSortedMatrix from "./SearchInSortedMatrix";

const BinarySearchMain = () => {
  // BinarySearch();
  // BitonicArrayMaximum();
  // CeilingOfANumber();
  // CountOfRangeSum();
  // FindKClosestElements();
  // FindMinimumInRotatedSortedArray();
  // FindPeakElement();
  // FindThreeLargestNums();
  // FindSmallestLetterGreaterThanTarget();
  // MedianOfTwoSortedArrays();
  // MinimumDifferenceElement();
  // NextLetter();
  // NumberRange();
  // OrderAgnosticBinarySearch();
  // PeakIndexInAMountainArray();
  // RotationCount();
  // SearchA2DMatrix();
  // SearchA2DMatrix2();
  // SearchInASortedInfiniteArray();
  // SearchInSortedMatrix();
  // SearchBitonicArray();
  // SearchInRotatedArray();
  // SearchInRotatedArray2();
};

export default BinarySearchMain;
