import BalancedBrackets from './BalancedBrackets';
import BasicCalculator2 from './BasicCalculator2';
import DailyTemperatures from './DailyTemperatures';
import ExclusiveTimeOfFunctions from './ExclusiveTimeOfFunctions';
import MaximumFrequencyStack from './MaximumFrequencyStack';
import MinimumAddToMakeParenthesesValid from './MinimumAddToMakeParenthesesValid';
import MinimumRemoveToMakeValidParentheses from './MinimumRemoveToMakeValidParentheses';
import MinMaxStackConstruction from './MinMaxStackConstruction';
import MinStack from './MinStack';
import NextGreaterElement from './NextGreaterElement';
import NextGreaterElementLeetcode from './NextGreaterElementLeetcode';
import SortStack from './SortStack';
import SumOfSubarrayMinimums from './SumOfSubarrayMinimums';
import SumOfSubarrayRanges from './SumOfSubarrayRanges';
import SunsetViews from './SunsetViews';
import ValidParentheses from './ValidParentheses';

export default () => {
  // BasicCalculator2();
  // BalancedBrackets();
  // DailyTemperatures();
  // ExclusiveTimeOfFunctions();
  // MaximumFrequencyStack();
  // MinimumAddToMakeParenthesesValid();
  // MinimumRemoveToMakeValidParentheses();
  // MinMaxStackConstruction();
  // MinStack();
  // NextGreaterElement();
  // NextGreaterElementLeetcode();
  // SortStack();
  // SumOfSubarrayMinimums();
  // SumOfSubarrayRanges();
  // SunsetViews();
  // ValidParentheses();
};
