import AddStrings from './AddStrings';
import CountPrimes from './CountPrimes';
import ExcelSheetColumnNumber from './ExcelSheetColumnNumber';
import FactorialTrailingZeroes from './FactorialTrailingZeroes';
import FindMedianFromDataStream from './FindMedianFromDataStream';
import FindNUniqueIntegersSumUpToZero from './FindNUniqueIntegersSumUpToZero';
import FractionToRecurringDecimal from './FractionToRecurringDecimal';
import HappyNumber from './HappyNumber';
import PlusOne from './PlusOne';
import PowerOfThree from './PowerOfThree';
import PowXN from './PowXN';
import RandomPickWithWeight from './RandomPickWithWeight';
import Sqrtx from './Sqrtx';
import TheKthFactorOfN from './TheKthFactorOfN';
import ValidNumber from './ValidNumber';

export default () => {
  // AddStrings();
  // CountPrimes();
  // ExcelSheetColumnNumber();
  // FactorialTrailingZeroes();
  // FindMedianFromDataStream();
  // FindNUniqueIntegersSumUpToZero();
  // FractionToRecurringDecimal();
  // HappyNumber();
  // TheKthFactorOfN();
  // PlusOne();
  // PowerOfThree();
  // PowXN();
  // RandomPickWithWeight();
  // Sqrtx();
  // ValidNumber();
};
