import TreesMain from './Trees/TreesMain';
import ArraysMain from './Arrays/ArraysMain';
import BinaryMain from './Binary/BinaryMain';
import LinkedListMain from './LinkedLists/LinkedListMain';
import HeapsMain from './Heaps/HeapsMain';
import MathMain from './Math/MathMain';
import MatrixMain from './Matrix/MatrixMain';
import QueuesMain from './Queues/QueuesMain';
import RecursionMain from './Recursion/RecursionMain';
import StacksMain from './Stacks/StacksMain';
import SortingMain from './Sorting/SortingMain';
import StringsMain from './Strings/StringsMain';
import DPMain from './DP/DPMain';
import GraphsMain from './Graphs/GraphsMain';
import Sketch from './Sketch';
import SlidingWindowMain from './SlidingWindow/SlidingWindowMain';
import FastAndSlowPointersMain from './FastAndSlowPointers/FastAndSlowPointersMain';
import IntervalsMain from './Intervals/IntervalsMain';
import CyclicSortMain from './CyclicSort/CyclicSortMain';
import LinkedListReversalMain from './LinkedListReversal/LinkedListReversalMain';
import TreeBFSMain from './TreeBFS/TreeBFSMain';
import TreeDFSMain from './TreeDFS/TreeDFSMain';
import TwoHeapsMain from './TwoHeaps/TwoHeapsMain';
import SubsetsMain from './Subsets/SubsetsMain';
import TopKElementsMain from './TopKElements/TopKElementsMain';
import KWayMergeMain from './KWayMerge/KWayMergeMain';
import KnapsackDPMain from './KnapsackDP/KnapsackDPMain';
import TopologicalGraphSortMain from './TopologicalGraphSort/TopologicalGraphSortMain';
import GreedyMain from './Greedy/GreedyMain';
import BinarySearch from './BinarySearch/BinarySearch';
import BinarySearchMain from './BinarySearch/BinarySearchMain';
import ObjectOrientationMain from './ObjectOrientation/ObjectOrientationMain';
import BinarySearchTreeMain from './BinarySearchTree/BinarySearchTreeMain';
import PointersMain from './Pointers/PointersMain';
import TrieMain from './Trie/TrieMain';

function main() {
  // Sketch();
  // ArraysMain();
  // BinaryMain();
  // BinarySearchMain();
  // BinarySearchTreeMain();
  // CyclicSortMain();
  // DPMain();
  // FastAndSlowPointersMain();
  // GraphsMain();
  // GreedyMain();
  // HeapsMain();
  // IntervalsMain()
  // LinkedListReversalMain();
  // LinkedListMain();
  // KnapsackDPMain();
  // KWayMergeMain();
  // MathMain();
  // MatrixMain();
  // ModifiedBinarySearchMain();
  // ObjectOrientationMain();
  // PointersMain();
  // QueuesMain();
  // RecursionMain();
  // SortingMain();
  // SlidingWindowMain();
  // StacksMain();
  // StringsMain();
  // SubsetsMain();
  // TopKElementsMain();
  // TopologicalGraphSortMain();
  // TreeBFSMain();
  // TreeDFSMain();
  // TreesMain();
  TrieMain();
  // TwoHeapsMain();
}

main();
