import TreesMain from './Trees/TreesMain';
import ArraysMain from './Arrays/ArraysMain';
import BinaryMain from './Binary/BinaryMain';
import LinkedListMain from './LinkedLists/LinkedListMain';
import HeapsMain from './Heaps/HeapsMain';
import MathMain from './Math/MathMain';
import MatrixMain from './Matrix/MatrixMain';
import QueuesMain from './Queues/QueuesMain';
import RecursionMain from './Recursion/RecursionMain';
import StacksMain from './Stacks/StacksMain';
import SortingMain from './Sorting/SortingMain';
import StringsMain from './Strings/StringsMain';
import DPMain from './DP/DPMain';
import GraphsMain from './Graphs/GraphsMain';
import Sketch from './Sketch';
import SlidingWindowMain from './SlidingWindow/SlidingWindowMain';
import TwoPointersMain from './TwoPointers/TwoPointersMain';
import FastAndSlowPointersMain from './FastAndSlowPointers/FastAndSlowPointersMain';
import IntervalsMain from './Intervals/IntervalsMain';
import CyclicSortMain from './CyclicSort/CyclicSortMain';
import LinkedListReversalMain from './LinkedListReversal/LinkedListReversalMain';
import TreeBFSMain from './TreeBFS/TreeBFSMain';
import TreeDFSMain from './TreeDFS/TreeDFSMain';
import TwoHeapsMain from './TwoHeaps/TwoHeapsMain';
import SubsetsMain from './Subsets/SubsetsMain';
import ModifiedBinarySearchMain from './ModifiedBinarySearch/ModifiedBinarySearchMain';
import TopKElementsMain from './TopKElements/TopKElementsMain';
import KWayMergeMain from './KWayMerge/KWayMergeMain';

function main() {
    // Sketch();
    // ArraysMain();
    // BinaryMain();
    // CyclicSortMain();
    // DPMain();
    // FastAndSlowPointersMain();
    // GraphsMain();
    // HeapsMain();
    // IntervalsMain()
    // LinkedListReversalMain();
    // LinkedListMain();
    KWayMergeMain();
    // MathMain();
    // MatrixMain();
    // ModifiedBinarySearchMain();
    // QueuesMain();
    // RecursionMain();
    // SortingMain();
    // SlidingWindowMain();
    // StacksMain();
    // StringsMain();
    // SubsetsMain();
    // TopKElementsMain();
    // TreeBFSMain();
    // TreeDFSMain();
    // TreesMain();
    // TwoHeapsMain();
    // TwoPointersMain();
}

main();
