import FindNumbersWithEvenDigits from './FindNumbersWithEvenDigits';
import TwoSum1 from './TwoSum1';
import TwoSum2 from './TwoSum2';
import SingleNumber from './SingleNumber';
import MoveZeroes from './MoveZeroes';
import MajorityElement from './MajorityElement';
import FindDisappearedNumbersInArray from './FindDisappearedNumbers';
import BestTimeToBuyAndSellStock from './BestTimeToBuyAndSellStock';
import MaximumSubarray from './MaximumSubarray';
import ShortestUnsortedContinuousSubarray from './ShortestUnsortedContinuousSubarray';
import TopKFrequentElements from './TopKFrequentElements';
import ProductOfArrayExceptSelf from './ProductOfArrayExceptSelf';
import FindTheDuplicateNumber from './FindTheDuplicateNumber';
import GroupAnagrams from './GroupAnagrams';
import ContainerWithMostWater from './ContainerWithMostWater';
import TaskScheduler from './TaskScheduler';
import SortColors from './SortColors';
import FindFirstAndLostPositionOfElement from './FindFirstAndLastPositionofElement';
import SearchInRotatedSortedArray from './SearchInRotatedSortedArray';
import NextPermutation from './NextPermutation';
import MaxProductSubarray from './MaximumProductSubarray';
import LRUCache from './LRUCache';
import LongestSubstringWithoutRepeatingCharacters from './LongestSubstrWithoutRepeatingChars';
import LongestPalindromicSubstring from './LongestPalindromicSubstring';
import SquaresOfASortedArray from './SquaresOfASortedArray';
import ThreeSum from './ThreeSum';
import BurstBalloons from './BurstBalloons';

const ArraysMain = () => {
    // FindNumbersWithEvenDigits();
    // TwoSum1();
    // TwoSum2();
    // SingleNumber();
    // MoveZeroes();
    // MajorityElement();
    // FindDisappearedNumbersInArray();
    // BestTimeToBuyAndSellStock();
    // MaximumSubarray();
    // ShortestUnsortedContinuousSubarray();
    // TopKFrequentElements();
    // ProductOfArrayExceptSelf();
    // FindTheDuplicateNumber();
    // GroupAnagrams();
    // ContainerWithMostWater();
    // TaskScheduler();
    // SortColors();
    // FindFirstAndLostPositionOfElement();
    // SearchInRotatedSortedArray();
    // NextPermutation();
    // MaxProductSubarray();
    // LRUCache();
    // LongestSubstringWithoutRepeatingCharacters();
    // LongestPalindromicSubstring();
    // SquaresOfASortedArray();
    // ThreeSum();
    BurstBalloons();
};

export default ArraysMain;
