import FindNumbersWithEvenDigits from './FindNumbersWithEvenDigits';
import TwoSum1 from './TwoSum1';
import TwoSum2 from './TwoSum2';
import SingleNumber from './SingleNumber';
import MoveZeroes from './MoveZeroes';
import MajorityElement from './MajorityElement';
import FindDisappearedNumbersInArray from './FindDisappearedNumbers';
import BestTimeToBuyAndSellStock from './BestTimeToBuyAndSellStock';
import MaximumSubarray from './MaximumSubarray';
import ShortestUnsortedContinuousSubarray from './ShortestUnsortedContinuousSubarray';
import TopKFrequentElements from './TopKFrequentElements';
import ProductOfArrayExceptSelf from './ProductOfArrayExceptSelf';
import FindTheDuplicateNumber from './FindTheDuplicateNumber';
import GroupAnagrams from './GroupAnagrams';
import ContainerWithMostWater from './ContainerWithMostWater';
import TaskScheduler from './TaskScheduler';
import SortColors from './SortColors';
import FindFirstAndLostPositionOfElement from './FindFirstAndLastPositionofElement';
import SearchInRotatedSortedArray from './SearchInRotatedSortedArray';
import NextPermutation from './NextPermutation';
import MaxProductSubarray from './MaximumProductSubarray';
import LRUCache from './LRUCache';
import LongestSubstringWithoutRepeatingCharacters from './LongestSubstrWithoutRepeatingChars';
import LongestPalindromicSubstring from './LongestPalindromicSubstring';
import SquaresOfASortedArray from './SquaresOfASortedArray';
import ThreeSum from './ThreeSum';
import ContainsDuplicate from './ContainsDuplicate';
import BestTimeToBuyAndSellStock2 from './BestTimeToBuyAndSellStock2';
import PascalsTriangle from './PascalsTriangle';
import MissingNumber from './MissingNumber';
import IntersectionOfTwoArrays2 from './IntersectionOfTwoArrays2';
import RemoveDuplicatesFromSortedArray from './RemoveDuplicatesFromSortedArray';
import MergeSortedArray from './MergeSortedArray';
import LongestCommonPrefix from './LongestCommonPrefix';
import KthLargestElementInArray from './KthLargestElementInArray';
import FourSum2 from './FourSum2';
import ArrayQuadruplet from './ArrayQuadruplet';
import CountGoodTriplets from './CountGoodTriplets';
import MinimumTimeVisitingAllPoints from './MinimumTimeVisitingAllPoints';
import SearchInsertPosition from './SearchInsertPosition';
import TrappingRainWater from './TrappingRainWater';
import ValidateSubsequence from './ValidateSubsequence';
import SortedSquaredArray from './SortedSquaredArray';
import TournamentWinner from './TournamentWinner';
import NonConstructableChange from './NonConstructableChange';
import SmallestDifference from './SmallestDifference';
import MoveElementToEnd from './MoveElementToEnd';
import MonotonicArray from './MonotonicArray';
import LongestPeak from './LongestPeak';
import FirstDuplicateValue from './FirstDuplicateValue';
import FourSum from './FourSum';
import LargestRange from './LargestRange';
import MinRewards from './MinRewards';
import ApartmentHunting from './ApartmentHunting';
import Quickselect from './Quickselect';
import IndexEqualsValue from './IndexEqualsValue';
import KadanesAlgorithm from './KadanesAlgorithm';
import FindAllDuplicatesInAnArray from './FindAllDuplicatesInAnArray';
import LongestConsecutiveSubsequence from './LongestConsecutiveSubsequence';
import MinimumAreaRectangle from './MinimumAreaRectangle';
import LineThroughPoints from './LineThroughPoints';
import FirstMissingPositive from './FirstMissingPositive';

const ArraysMain = () => {
    // ArrayQuadruplet();
    // ApartmentHunting();
    // BestTimeToBuyAndSellStock();
    // BestTimeToBuyAndSellStock2();
    // ContainerWithMostWater();
    // ContainsDuplicate();
    // CountGoodTriplets();
    // FindAllDuplicatesInAnArray();
    // FindDisappearedNumbersInArray();
    // FindFirstAndLostPositionOfElement();
    // FindNumbersWithEvenDigits();
    // FindTheDuplicateNumber();
    // FirstDuplicateValue();
    FirstMissingPositive();
    // FourSum();
    // FourSum2();
    // GroupAnagrams();
    // IndexEqualsValue();
    // IntersectionOfTwoArrays2();
    // KadanesAlgorithm();
    // KthLargestElementInArray();
    // LargestRange();
    // LineThroughPoints();
    // LongestCommonPrefix();
    // LongestConsecutiveSubsequence();
    // LongestPalindromicSubstring();
    // LongestPeak();
    // LongestSubstringWithoutRepeatingCharacters();
    // LRUCache();
    // MajorityElement();
    // MaximumSubarray();
    // MaxProductSubarray();
    // MergeSortedArray();
    // MinimumAreaRectangle();
    // MinRewards();
    // MonotonicArray();
    // MoveElementToEnd();
    // MinimumTimeVisitingAllPoints();
    // MissingNumber();
    // MoveZeroes();
    // NextPermutation();
    // NonConstructableChange();
    // PascalsTriangle();
    // ProductOfArrayExceptSelf();
    // Quickselect();
    // RemoveDuplicatesFromSortedArray();
    // SearchInRotatedSortedArray();
    // SearchInsertPosition();
    // ShortestUnsortedContinuousSubarray();
    // SmallestDifference();
    // SingleNumber();
    // SortColors();
    // SortedSquaredArray();
    // SquaresOfASortedArray();
    // TaskScheduler();
    // TrappingRainWater();
    // TopKFrequentElements();
    // TournamentWinner();
    // TwoSum1();
    // TwoSum2();
    // ThreeSum();
    // ValidateSubsequence();
};

export default ArraysMain;
